# Generated by Django 6.0.3 on 2026-03-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner')], default='customer', max_length=20),
        ),
    ]
