# Generated by Django 6.0.3 on 2026-03-25 05:53

import dryMe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dryMe.models.shop_image_upload),
        ),
    ]
