# Generated by Django 6.0.3 on 2026-03-25 08:43

import dryMe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0005_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dryMe.models.shop_image_upload),
        ),
    ]
