# Generated by Django 6.0.3 on 2026-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0008_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
