# Generated by Django 6.0.3 on 2026-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0010_remove_order_address_remove_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
