# Generated by Django 6.0.3 on 2026-03-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0012_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
