# Generated by Django 6.0.3 on 2026-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0013_user_phone_user_subscription_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_expiry',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
