# Generated by Django 6.0.3 on 2026-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0014_remove_user_subscription_expiry_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('washing', 'Washing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
