# Generated by Django 6.0.5 on 2026-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0016_shop_created_at_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
