# Generated by Django 6.0.5 on 2026-05-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0017_alter_order_options_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
