# Generated by Django 6.0.5 on 2026-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0018_order_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
