# Generated by Django 6.0.5 on 2026-05-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0019_order_archived_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='archived',
            new_name='customer_archived',
        ),
        migrations.RemoveField(
            model_name='order',
            name='archived_at',
        ),
        migrations.AddField(
            model_name='order',
            name='owner_archived',
            field=models.BooleanField(default=False),
        ),
    ]
