# Generated by Django 6.0.5 on 2026-06-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0020_rename_archived_order_customer_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
