# Generated by Django 6.0.5 on 2026-06-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryMe', '0021_remove_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
